### ISSUE TITLE
同步 anaconda nvidia 频道的 label

### ISSUE THREAD

**Issue by moetayuko** [SUSTech-CRA/issues#13]
该频道的部分包在安装时使用 label 来保证相互的兼容性，如：https://anaconda.org/nvidia/cuda-libraries-dev

但目前没有同步 label，导致安装时出现类似错误：
```
❯ conda install -c "nvidia/label/cuda-11.8.0" cuda-nvcc cuda-libraries-dev
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel nvidia/label/cuda-11.8.0 <https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

希望能对 label 也进行镜像，方式类似 https://github.com/tuna/tunasync-scripts/blob/b5f2aad04c598b8e4dee173d3c2eeefa0e5dc24c/anaconda.py#L57

**Comment by sparkcyf** [comment]
你好，我们注意到各版本label下的软件和 `nvidia/linux-64/` 下的软件包基本一致。我们将在近期尝试用软链接的方式实现这个镜像，计划在六月末前完成。

**Comment by sparkcyf** [comment]
已使用软链接 https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/linux-64/ 的方式完成镜像。

**Comment by moetayuko** [comment]
目前的方案似乎有些问题。

每个`label/cuda-xxx/linux-64`下应仅包含与label版本对应的包，以`cuda-11.8.0`为例，相应的包版本在https://anaconda.org/nvidia/repo/files?type=conda&label=cuda-11.8.0 列出

但目前各个label的文件夹下都有所有版本的包（即https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/linux-64/ 与 https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64/ 的内容完全一致），从label安装就没有意义了。

具体来说，`conda install -c "nvidia/label/cuda-11.8.0" cuda-libraries-dev`时，官方源的版本如下：
```
  cuda-cccl          nvidia/label/cuda-11.8.0/linux-64::cuda-cccl-11.8.89-0
  cuda-cudart        nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-11.8.89-0
  cuda-cudart-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-dev-11.8.89-0
  cuda-driver-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-driver-dev-11.8.89-0
  cuda-libraries-dev nvidia/label/cuda-11.8.0/linux-64::cuda-libraries-dev-11.8.0-0
  cuda-nvrtc         nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-11.8.89-0
  cuda-nvrtc-dev     nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-dev-11.8.89-0
  cuda-profiler-api  nvidia/label/cuda-11.8.0/linux-64::cuda-profiler-api-11.8.86-0
  libcublas          nvidia/label/cuda-11.8.0/linux-64::libcublas-11.11.3.6-0
  libcublas-dev      nvidia/label/cuda-11.8.0/linux-64::libcublas-dev-11.11.3.6-0
  libcufft           nvidia/label/cuda-11.8.0/linux-64::libcufft-10.9.0.58-0
  libcufft-dev       nvidia/label/cuda-11.8.0/linux-64::libcufft-dev-10.9.0.58-0
  libcufile          nvidia/label/cuda-11.8.0/linux-64::libcufile-1.4.0.31-0
  libcufile-dev      nvidia/label/cuda-11.8.0/linux-64::libcufile-dev-1.4.0.31-0
  libcurand          nvidia/label/cuda-11.8.0/linux-64::libcurand-10.3.0.86-0
  libcurand-dev      nvidia/label/cuda-11.8.0/linux-64::libcurand-dev-10.3.0.86-0
  libcusolver        nvidia/label/cuda-11.8.0/linux-64::libcusolver-11.4.1.48-0
  libcusolver-dev    nvidia/label/cuda-11.8.0/linux-64::libcusolver-dev-11.4.1.48-0
  libcusparse        nvidia/label/cuda-11.8.0/linux-64::libcusparse-11.7.5.86-0
  libcusparse-dev    nvidia/label/cuda-11.8.0/linux-64::libcusparse-dev-11.7.5.86-0
  libnpp             nvidia/label/cuda-11.8.0/linux-64::libnpp-11.8.0.86-0
  libnpp-dev         nvidia/label/cuda-11.8.0/linux-64::libnpp-dev-11.8.0.86-0
  libnvjpeg          nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-11.9.0.86-0
  libnvjpeg-dev      nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-dev-11.9.0.86-0
```
而镜像源的版本如下：
```
  cuda-cccl          nvidia/label/cuda-11.8.0/linux-64::cuda-cccl-12.1.109-0
  cuda-cudart        nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-12.1.105-0
  cuda-cudart-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-dev-12.1.105-0
  cuda-driver-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-driver-dev-12.1.105-0
  cuda-libraries-dev nvidia/label/cuda-11.8.0/linux-64::cuda-libraries-dev-12.1.1-0
  cuda-nvrtc         nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-12.1.105-0
  cuda-nvrtc-dev     nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-dev-12.1.105-0
  cuda-opencl        nvidia/label/cuda-11.8.0/linux-64::cuda-opencl-12.1.105-0
  cuda-opencl-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-opencl-dev-12.1.105-0
  cuda-profiler-api  nvidia/label/cuda-11.8.0/linux-64::cuda-profiler-api-12.1.105-0
  libcublas          nvidia/label/cuda-11.8.0/linux-64::libcublas-12.1.3.1-0
  libcublas-dev      nvidia/label/cuda-11.8.0/linux-64::libcublas-dev-12.1.3.1-0
  libcufft           nvidia/label/cuda-11.8.0/linux-64::libcufft-11.0.2.54-0
  libcufft-dev       nvidia/label/cuda-11.8.0/linux-64::libcufft-dev-11.0.2.54-0
  libcufile          nvidia/label/cuda-11.8.0/linux-64::libcufile-1.6.1.9-0
  libcufile-dev      nvidia/label/cuda-11.8.0/linux-64::libcufile-dev-1.6.1.9-0
  libcurand          nvidia/label/cuda-11.8.0/linux-64::libcurand-10.3.2.106-0
  libcurand-dev      nvidia/label/cuda-11.8.0/linux-64::libcurand-dev-10.3.2.106-0
  libcusolver        nvidia/label/cuda-11.8.0/linux-64::libcusolver-11.4.5.107-0
  libcusolver-dev    nvidia/label/cuda-11.8.0/linux-64::libcusolver-dev-11.4.5.107-0
  libcusparse        nvidia/label/cuda-11.8.0/linux-64::libcusparse-12.1.0.106-0
  libcusparse-dev    nvidia/label/cuda-11.8.0/linux-64::libcusparse-dev-12.1.0.106-0
  libnpp             nvidia/label/cuda-11.8.0/linux-64::libnpp-12.1.0.40-0
  libnpp-dev         nvidia/label/cuda-11.8.0/linux-64::libnpp-dev-12.1.0.40-0
  libnvjitlink       nvidia/label/cuda-11.8.0/linux-64::libnvjitlink-12.1.105-0
  libnvjitlink-dev   nvidia/label/cuda-11.8.0/linux-64::libnvjitlink-dev-12.1.105-0
  libnvjpeg          nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-12.2.0.2-0
  libnvjpeg-dev      nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-dev-12.2.0.2-0
```

进行镜像操作时，是否可以获取官方源`nvidia/label/cuda-xxx/linux-64`目录下的文件列表，再从`nvidia/linux-64`软链接单个文件过去？

**Comment by sparkcyf** [comment]
> 目前的方案似乎有些问题。
> 
> 每个`label/cuda-xxx/linux-64`下应仅包含与label版本对应的包，以`cuda-11.8.0`为例，相应的包版本在https://anaconda.org/nvidia/repo/files?type=conda&label=cuda-11.8.0 列出
> 
> 但目前各个label的文件夹下都有所有版本的包（即https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/linux-64/ 与 https://mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64/ 的内容完全一致），从label安装就没有意义了。
> 
> 具体来说，`conda install -c "nvidia/label/cuda-11.8.0" cuda-libraries-dev`时，官方源的版本如下：
> 
> ```
>   cuda-cccl          nvidia/label/cuda-11.8.0/linux-64::cuda-cccl-11.8.89-0
>   cuda-cudart        nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-11.8.89-0
>   cuda-cudart-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-dev-11.8.89-0
>   cuda-driver-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-driver-dev-11.8.89-0
>   cuda-libraries-dev nvidia/label/cuda-11.8.0/linux-64::cuda-libraries-dev-11.8.0-0
>   cuda-nvrtc         nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-11.8.89-0
>   cuda-nvrtc-dev     nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-dev-11.8.89-0
>   cuda-profiler-api  nvidia/label/cuda-11.8.0/linux-64::cuda-profiler-api-11.8.86-0
>   libcublas          nvidia/label/cuda-11.8.0/linux-64::libcublas-11.11.3.6-0
>   libcublas-dev      nvidia/label/cuda-11.8.0/linux-64::libcublas-dev-11.11.3.6-0
>   libcufft           nvidia/label/cuda-11.8.0/linux-64::libcufft-10.9.0.58-0
>   libcufft-dev       nvidia/label/cuda-11.8.0/linux-64::libcufft-dev-10.9.0.58-0
>   libcufile          nvidia/label/cuda-11.8.0/linux-64::libcufile-1.4.0.31-0
>   libcufile-dev      nvidia/label/cuda-11.8.0/linux-64::libcufile-dev-1.4.0.31-0
>   libcurand          nvidia/label/cuda-11.8.0/linux-64::libcurand-10.3.0.86-0
>   libcurand-dev      nvidia/label/cuda-11.8.0/linux-64::libcurand-dev-10.3.0.86-0
>   libcusolver        nvidia/label/cuda-11.8.0/linux-64::libcusolver-11.4.1.48-0
>   libcusolver-dev    nvidia/label/cuda-11.8.0/linux-64::libcusolver-dev-11.4.1.48-0
>   libcusparse        nvidia/label/cuda-11.8.0/linux-64::libcusparse-11.7.5.86-0
>   libcusparse-dev    nvidia/label/cuda-11.8.0/linux-64::libcusparse-dev-11.7.5.86-0
>   libnpp             nvidia/label/cuda-11.8.0/linux-64::libnpp-11.8.0.86-0
>   libnpp-dev         nvidia/label/cuda-11.8.0/linux-64::libnpp-dev-11.8.0.86-0
>   libnvjpeg          nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-11.9.0.86-0
>   libnvjpeg-dev      nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-dev-11.9.0.86-0
> ```
> 
> 而镜像源的版本如下：
> 
> ```
>   cuda-cccl          nvidia/label/cuda-11.8.0/linux-64::cuda-cccl-12.1.109-0
>   cuda-cudart        nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-12.1.105-0
>   cuda-cudart-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-dev-12.1.105-0
>   cuda-driver-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-driver-dev-12.1.105-0
>   cuda-libraries-dev nvidia/label/cuda-11.8.0/linux-64::cuda-libraries-dev-12.1.1-0
>   cuda-nvrtc         nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-12.1.105-0
>   cuda-nvrtc-dev     nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-dev-12.1.105-0
>   cuda-opencl        nvidia/label/cuda-11.8.0/linux-64::cuda-opencl-12.1.105-0
>   cuda-opencl-dev    nvidia/label/cuda-11.8.0/linux-64::cuda-opencl-dev-12.1.105-0
>   cuda-profiler-api  nvidia/label/cuda-11.8.0/linux-64::cuda-profiler-api-12.1.105-0
>   libcublas          nvidia/label/cuda-11.8.0/linux-64::libcublas-12.1.3.1-0
>   libcublas-dev      nvidia/label/cuda-11.8.0/linux-64::libcublas-dev-12.1.3.1-0
>   libcufft           nvidia/label/cuda-11.8.0/linux-64::libcufft-11.0.2.54-0
>   libcufft-dev       nvidia/label/cuda-11.8.0/linux-64::libcufft-dev-11.0.2.54-0
>   libcufile          nvidia/label/cuda-11.8.0/linux-64::libcufile-1.6.1.9-0
>   libcufile-dev      nvidia/label/cuda-11.8.0/linux-64::libcufile-dev-1.6.1.9-0
>   libcurand          nvidia/label/cuda-11.8.0/linux-64::libcurand-10.3.2.106-0
>   libcurand-dev      nvidia/label/cuda-11.8.0/linux-64::libcurand-dev-10.3.2.106-0
>   libcusolver        nvidia/label/cuda-11.8.0/linux-64::libcusolver-11.4.5.107-0
>   libcusolver-dev    nvidia/label/cuda-11.8.0/linux-64::libcusolver-dev-11.4.5.107-0
>   libcusparse        nvidia/label/cuda-11.8.0/linux-64::libcusparse-12.1.0.106-0
>   libcusparse-dev    nvidia/label/cuda-11.8.0/linux-64::libcusparse-dev-12.1.0.106-0
>   libnpp             nvidia/label/cuda-11.8.0/linux-64::libnpp-12.1.0.40-0
>   libnpp-dev         nvidia/label/cuda-11.8.0/linux-64::libnpp-dev-12.1.0.40-0
>   libnvjitlink       nvidia/label/cuda-11.8.0/linux-64::libnvjitlink-12.1.105-0
>   libnvjitlink-dev   nvidia/label/cuda-11.8.0/linux-64::libnvjitlink-dev-12.1.105-0
>   libnvjpeg          nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-12.2.0.2-0
>   libnvjpeg-dev      nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-dev-12.2.0.2-0
> ```
> 
> 进行镜像操作时，是否可以获取官方源`nvidia/label/cuda-xxx/linux-64`目录下的文件列表，再从`nvidia/linux-64`软链接单个文件过去？

抱歉，我在配置之后没有完整的测试，我这几天再修改一下脚本看看。

**Comment by sparkcyf** [comment]
```
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  + cuda-cccl             11.8.89  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64        1MB
  + cuda-cudart           11.8.89  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + cuda-cudart-dev       11.8.89  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64        1MB
  + cuda-driver-dev       11.8.89  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64       16kB
  + cuda-libraries-dev     11.8.0  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64        2kB
  + cuda-nvrtc            11.8.89  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + cuda-nvrtc-dev        11.8.89  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64       18MB
  + cuda-profiler-api     11.8.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64       19kB
  + libcublas           11.11.3.6  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + libcublas-dev       11.11.3.6  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64      413MB
  + libcufft            10.9.0.58  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + libcufft-dev        10.9.0.58  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64      289MB
  + libcufile            1.4.0.31  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64      561kB
  + libcufile-dev        1.4.0.31  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64        2MB
  + libcurand           10.3.0.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64       56MB
  + libcurand-dev       10.3.0.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64       56MB
  + libcusolver         11.4.1.48  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + libcusolver-dev     11.4.1.48  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64       70MB
  + libcusparse         11.7.5.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + libcusparse-dev     11.7.5.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64      377MB
  + libnpp              11.8.0.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + libnpp-dev          11.8.0.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64      151MB
  + libnvjpeg           11.9.0.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64     Cached
  + libnvjpeg-dev       11.9.0.86  0      mirrors.sustech.edu.cn/anaconda-extra/cloud/nvidia/label/cuda-11.8.0/linux-64        2MB
```

@MoetaYuko 在更换了新的软链接方法之后我这边看起来没问题了，你这边方便测试一下吗？

**Comment by moetayuko** [comment]
似乎没有问题了，多谢

**Comment by LiNY2-01** [comment]
你好，目前各个label的文件夹下都有所有版本的包，导致从label中安装nvidia包会默认安装最新的12.6版本。
