### ISSUE TITLE
Archlinux 官方以及相关源同步频率应该提升

### ISSUE THREAD

**Issue by LC0117** [SUSTech-CRA/issues#15]
arch官方仓库有时更新较频繁，作为一个使用者，经常会出现短时间内（一天内）收到多个revision级别的更新。同时，archlinuxcn的某些仓库包在涉及到arch包升级触发的rebuild也会有小时级别的lag。这两个源的更新频率应该提升确保获得上游最新的修复（可参考tuna源的更新频率）。

**Comment by taotieren** [comment]
补充一个 mirrorz 的配置问题。

> `https://mirrors.sustech.edu.cn/mirrorz/mirrorz.json` 中没有提供省份信息

https://github.com/mirrorz-org/mirrorz/issues/110#issuecomment-1725117452

**Comment by sparkcyf** [comment]
收到，已将同步频率提高至4小时/次。
