### ISSUE TITLE
开启压缩优化

### ISSUE THREAD

**Issue by cao-gift** [SUSTech-CRA/issues#19]
如

staticfile
https://cdn.staticfile.net/Primer/21.0.7/primer.css
CDNJS
https://cdnjs.cloudflare.com/ajax/libs/Primer/21.0.7/primer.css
南科大
https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/Primer/21.0.7/primer.css
南科大的这个源网络传输的primer.css有833kB，而CDNJS只有41.1kB，staticfile有107kB，staticfile 的压缩算法是 gzip，cloudflare 是 brotli，南科大没有启用压缩。 cloudflare 使用的 brotli 的压缩能力与速度都更快，所以比 staticfile 小，南科大原样传递所以是文件原本大小。

如果考虑压缩，那么南科大确实不占优势。

**Comment by sparkcyf** [comment]
<img width="449" alt="image" src="https://github.com/SUSTech-CRA/issues/assets/14960340/3e7b8fea-e491-44fe-9b73-0d693555dbe7">
<img width="287" alt="image" src="https://github.com/SUSTech-CRA/issues/assets/14960340/14ac861a-fc94-41dc-bd08-4f37e9bb92f9">

您好，我们是开了brotli压缩的。请问您可以提供一下chrome dev tools里的Content-Encoding:供我们调查吗？

**Comment by cao-gift** [comment]
感谢，的确压缩了
![3](https://github.com/SUSTech-CRA/issues/assets/65548967/d5793472-5c97-445c-8541-65e83d127182)
