### ISSUE TITLE
校外无法访问sharelatex

### ISSUE THREAD

**Issue by rd-pong** [SUSTech-CRA/issues#2]
用移动网络无法校外访问sharelatex但可以正常访问cra.moe

**Comment by IgnotaYun** [comment]
据 DNS 记录，[sharelatex.cra.moe](https://sharelatex.cra.moe) 仅向公网提供 IPv6 服务，请尝试在 IPv6 网络环境下访问；
同时，[sharelatex.sustcra.com](https://sharelatex.sustcra.com) 提供了公网 IPv4 服务。
当然，您也可以选择使用回校 VPN。
