### ISSUE TITLE
请求增加Termux镜像

### ISSUE THREAD

**Issue by 2096779623** [SUSTech-CRA/issues#5]
# 项目名称
Termux
# 项目简介
Termux 是一款Android 终端模拟器和 Linux 环境应用程序，无需 root 或设置即可直接运行。自动安装最小的基本系统 - 使用 APT 包管理器可以使用其他包。
# 镜像方法
https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories
# 镜像大小
15GB

**Comment by IgnotaYun** [comment]
同步完成，已上线。

[mirrors.s.e.c/termux/](https://mirrors.sustech.edu.cn/termux/)
